### ISSUE TITLE
Does it support bi-direction

### ISSUE THREAD

**Issue by lbaitemple** [pololu/dual-mc33926-motor-shield#7]
I tried the code for port 1 using md.setM1Speed(200); and md.setM1Speed(-200). In both cases, the motor spins one direction.

**Comment by ryantm** [comment]
Hello, @lbaitemple 

Yes, the Pololu Dual MC33926 Motor Driver Shield for Arduino supports bi-directional control of two motors.  Since you are having issues with direction, I would check the connectivity (most likely a solder joint) between M1DIR and Arduino pin 7. Also, check your code for potential overlapping use of pin 7. 

If you are still having trouble, please ask for support on the [Pololu Forum](https://forum.pololu.com). GitHub issues are meant to track issues with the library code and are not meant for general technical support.

Sincerely,
Ryan Mulligan
